#!/usr/bin/env python3
"""
Build the vault's README files from each part's metadata.

    python3 scripts/build_readme.py          # write README.md + parts/*/README.md
    python3 scripts/build_readme.py --check  # exit 1 if any README is out of date

Source of truth: parts/<NN-name>/_production/meta.json. Never hand-edit a
generated README; change the meta.json and run this again. Standard library only.
"""
import json
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PARTS = ROOT / "parts"
VAULT_URL = "https://github.com/that-abhishek/ai-architecture-vault"
IG_URL = "https://instagram.com/ai.transition"
GENERATED = "<!-- Generated by scripts/build_readme.py from _production/meta.json. Edit that, not this. -->"

REQUIRED = ["part", "name", "slug", "track", "question", "problem", "points_heading", "points"]


def load_parts():
    parts = []
    for meta_path in sorted(PARTS.glob("*/_production/meta.json")):
        meta = json.loads(meta_path.read_text())
        folder = meta_path.parent.parent
        missing = [k for k in REQUIRED if not meta.get(k)]
        if missing:
            sys.exit(f"{folder.name}: meta.json is missing {', '.join(missing)}")
        if meta["slug"] != folder.name:
            sys.exit(f"{folder.name}: meta.json slug is '{meta['slug']}', expected the folder name")
        meta["_dir"] = folder
        meta["_canvas"] = next((c for c in ("canvas.jpg", "canvas.png") if (folder / c).is_file()
                                and (folder / c).stat().st_size > 0), None)
        parts.append(meta)
    numbers = [p["part"] for p in parts]
    dupes = {n for n in numbers if numbers.count(n) > 1}
    if dupes:
        sys.exit(f"duplicate part numbers: {sorted(dupes)}")
    return sorted(parts, key=lambda p: p["part"])


def nice_date(iso):
    if not iso:
        return None
    d = date.fromisoformat(iso)
    return f"{d.day} {d.strftime('%b %Y')}"


def track_label(p):
    return "AI Product" if p["track"] == "product" else "Engineering"


def part_readme(p, by_number):
    n = f"{p['part']:02d}"
    lines = [GENERATED, "", f"# Part {n} · {p['name']}", ""]
    meta_line = [f"**{track_label(p)}**"]
    if p.get("reel_url"):
        meta_line.append(f"[Watch the reel]({p['reel_url']})")
    if nice_date(p.get("published")):
        meta_line.append(f"Published {nice_date(p['published'])}")
    lines += [" · ".join(meta_line), "", f"> {p['question']}", "", p["problem"], ""]

    if p["_canvas"]:
        lines += [f"![Whiteboard for Part {n}]({p['_canvas']})", ""]

    lines += [f"## {p['points_heading']}", ""]
    numbered = p["points_heading"].lower().endswith("rules")
    for i, point in enumerate(p["points"], 1):
        lines.append(f"{i}. {point}" if numbered else f"- {point}")
    lines.append("")

    if p.get("formula"):
        lines += ["## The formula", "", "$$", p["formula"], "$$", ""]

    code = p.get("code")
    if code:
        lines += ["## The code" if code.get("run") else "## The template", "",
                  f"[`{code['file']}`]({code['file']}). {code['what']}", ""]
        if code.get("run"):
            lines += ["```bash", code["run"], "```", "", "Standard library only. Running it executes the self-test.", ""]

    stands = p.get("stands_on")
    if stands and stands.get("part") in by_number:
        base = by_number[stands["part"]]
        lines += ["## Stands on", "",
                  f"[Part {base['part']:02d} · {base['name']}](../{base['slug']}/): {stands['why']}.", ""]

    lines += ["## In this folder", ""]
    if (p["_dir"] / "script.md").is_file():
        lines.append("- `script.md`: the full breakdown, and what was said on camera")
    prod = production_contents(p["_dir"] / "_production")
    if prod:
        lines.append(f"- `_production/`: {prod}")
    lines += ["", "[← All parts](../../README.md)", ""]
    return "\n".join(lines)


PROD_LABELS = [("cue-cards.md", "cue cards"), ("captions.srt", "captions"),
               ("canvas_reference.svg", "canvas source"), ("reel_cover.png", "cover"),
               ("meta.json", "metadata"), ("master_cut", "the master cut")]


def production_contents(folder):
    if not folder.is_dir():
        return ""
    names = [f.name for f in folder.iterdir()]
    found = [label for key, label in PROD_LABELS if any(n.startswith(key) for n in names)]
    if not found:
        return ""
    return found[0] if len(found) == 1 else ", ".join(found[:-1]) + " and " + found[-1]


def row(p):
    code = "✓" if p.get("code") else ""
    return (f"| {p['part']:02d} | [{p['name']}](parts/{p['slug']}/) | {p['question']} "
            f"| {track_label(p)} | {code} |")


def root_readme(parts):
    main = [p for p in reversed(parts) if p.get("format") != "early"]
    early = [p for p in parts if p.get("format") == "early"]
    header = "| Part | Reel | The question | Track | Code |\n|---|---|---|---|---|"
    lines = [
        GENERATED, "",
        "# AI Architecture Vault", "",
        f"The whiteboard, script and code behind every [@ai.transition]({IG_URL}) reel. "
        "Each part is one reel: something that breaks when you build with LLMs, the mechanism "
        "behind it, and the rules that fix it.", "",
        "**Came from a reel?** Find it below by the title on its cover. Each part's folder opens "
        "with the whiteboard, the rules and any code.", "",
        "**New here?** Start with [Part 16](parts/16-paid-twice/) for an agent that takes real "
        "actions, [Part 12](parts/12-half-the-tokens-3x-the-bill/) for what an LLM bill is made of, "
        "or [Part 11](parts/11-prompt-injection/) for prompt injection.", "",
        "## Parts", "", "Newest first.", "", header,
    ]
    lines += [row(p) for p in main]
    if early:
        lines += ["", "<details>",
                  f"<summary><b>Foundations, Parts {early[0]['part']:02d}–{early[-1]['part']:02d}</b> "
                  "(the early format: how the model itself works, no whiteboard canvas)</summary>",
                  "", header]
        lines += [row(p) for p in early]
        lines += ["", "</details>"]
    lines += ["", "## Tracks", "",
              "**Engineering** changes code inside a system you've already decided to build. "
              "**AI Product** changes what gets built, or whether. Every product part names the "
              "engineering part it stands on.", "",
              "## How a part folder is laid out", "",
              "`README.md` (start here) · `canvas.jpg` (the whiteboard) · the code or template, "
              "if the part has one · `script.md` (full breakdown) · `_production/` (cue cards, "
              "captions, metadata, master cut). Details in [CONTRIBUTING.md](CONTRIBUTING.md).", "",
              "## License", "", "[MIT](LICENSE)", ""]
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv
    parts = load_parts()
    by_number = {p["part"]: p for p in parts}
    outputs = {ROOT / "README.md": root_readme(parts)}
    for p in parts:
        outputs[p["_dir"] / "README.md"] = part_readme(p, by_number)

    stale = []
    for path, text in outputs.items():
        current = path.read_text() if path.exists() else None
        if current != text:
            stale.append(path.relative_to(ROOT))
            if not check:
                path.write_text(text)
    if check:
        if stale:
            print("out of date:", *stale, sep="\n  ")
            sys.exit(1)
        print(f"all {len(outputs)} READMEs up to date")
    else:
        print(f"wrote {len(stale)} of {len(outputs)} READMEs" + ("" if stale else " (no changes)"))


if __name__ == "__main__":
    main()
